apiVersion: v2
name: botium-box-advanced
description: Botium Box Advanced

type: application
version: 0.0.4
appVersion: 2.8.6

dependencies:
  - name: botium-box-prisma
    version: 2.0.6
    repository: 'file://../botium-box-prisma'
  - name: botium-box-redis
    version: 0.0.1
    repository: 'file://../botium-box-redis'
    condition: INSTALL_REDIS
  - name: botium-box-zap
    version: 0.0.1
    repository: 'file://../botium-box-zap'
    condition: INSTALL_ZAP
